# Generated by Django 5.1.7 on 2025-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vegetable', models.CharField(max_length=100, unique=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('total_purchase_price', models.FloatField(blank=True, null=True)),
                ('total_selling_price', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
