# Generated by Django 5.1.7 on 2025-03-28 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablesale',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
