# Generated by Django 5.1.7 on 2025-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_vegetablesale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablesale',
            name='vegetable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='vegetablesale',
            unique_together={('vegetable', 'date')},
        ),
    ]
