# Generated by Django 5.1.7 on 2025-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_vegetablesale_vegetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_purchase_price', models.FloatField(default=0.0)),
                ('total_selling_price', models.FloatField(default=0.0)),
                ('total_profit', models.FloatField(default=0.0)),
            ],
        ),
    ]
