# Generated by Django 5.1.7 on 2025-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_dailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='total_loss',
            field=models.FloatField(default=0.0),
        ),
    ]
