# Generated by Django 5.1.7 on 2025-04-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_dailysummary_total_loss'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vegetable', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('total_purchase', models.FloatField()),
                ('total_selling', models.FloatField()),
                ('profit', models.FloatField()),
                ('loss', models.FloatField()),
            ],
        ),
    ]
