# Generated by Django 5.1.7 on 2025-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_vegetablereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_purchase', models.FloatField(default=0)),
                ('total_selling', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('loss', models.FloatField(default=0)),
            ],
        ),
    ]
